@startuml UML_test_example
' run this to create a png file:
' plantuml -tpng "examples/UML_test_example.puml"

class LBPManager {
    +__init__(study)
    +calibrate(exp_nr)
    +push_to_server()
}

class EvaluationSystem {
    +__init__(weights)
    +add_evaluation_model()
    +run_evaluation_system(exp_params, visualize_flag)
}

class PredictionSystem {
    +__init__()
    +add_ml_model()
    +run_inference(exp_params, visualize_flag)
    +benchmark_models()
}

class Calibration {
    +__init__(params)
    +add_optimizer()
}

' Concrete Implementations from Examples
class PathDeviation <<EvaluationModel>> #ADD8E655 {
    +__init__(criteria)
    +add_feature_model(feature_model, name)
    +run_evaluation(exp_nr, visualize_flag)
}

class EnergyConsumption <<EvaluationModel>> #ADD8E655 {
    +__init__(criteria)
    +add_feature_model(feature_model, name)
    +run_evaluation(exp_nr, visualize_flag)
}

class PathDeviationFeatures <<FeatureModel>> #90EE9055 {
    +__init__(exp_params)
    +load_data(exp_nr)
    +run_feature_extraction(exp_nr, visualize_flag)
}

class EnergyConsumptionFeatures <<FeatureModel>> #90EE9055 {
    +__init__(exp_params)
    +load_data(exp_nr)
    +run_feature_extraction(exp_nr, visualize_flag)
}

class AirtableInterface <<DataInterface>> #eeb6ff55 {
    +__init__(airtable_client)
    +pull_from_db(study)
    +push_to_db(study, data)
}

class MultilayerPerceptron <<MLModel>> #FFFFE055 {
    +__init__(params)
    +forward_pass(input)
    +train(dataset)
}

class GaussianProcess <<MLModel>> #FFFFE055 {
    +__init__(params)
    +forward_pass(input)
    +train(dataset)
}

class EvolutionaryAlgorithm <<Optimizer>> #FFB6C155 {
    +__init__(params)
    +find_optimum(prediction_model)
}

class GradientDescent <<Optimizer>> #FFB6C155 {
    +__init__(params)
    +find_optimum(prediction_model)
}

' Relationships
LBPManager *-- Calibration
LBPManager *-- AirtableInterface

Calibration *-- EvaluationSystem
Calibration *-- PredictionSystem

EvaluationSystem o-- PathDeviation
EvaluationSystem o-- EnergyConsumption

PathDeviation o-- PathDeviationFeatures
EnergyConsumption o-- EnergyConsumptionFeatures

PredictionSystem o-- MultilayerPerceptron
PredictionSystem o-- GaussianProcess

Calibration o-- EvolutionaryAlgorithm
Calibration o-- GradientDescent

@enduml